# Generated by Django 4.2.1 on 2023-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Friday',
            },
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Monday',
            },
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Saturday',
            },
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Sunday',
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Thursday',
            },
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Tuesday',
            },
        ),
        migrations.CreateModel(
            name='Wednessday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(max_length=12)),
                ('Trip', models.CharField(max_length=50)),
                ('Time', models.TimeField(max_length=8)),
                ('Purpose', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=12)),
                ('BookedSeats', models.CharField(max_length=60)),
                ('NumberOfSeats', models.IntegerField(max_length=17)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Wednessday',
            },
        ),
    ]
