# Generated by Django 4.2.1 on 2023-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatAllocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='friday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='wednessday',
            name='Date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='wednessday',
            name='Day',
            field=models.CharField(max_length=12),
        ),
    ]
