# Generated by Django 4.2.1 on 2023-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatAllocation', '0002_alter_friday_date_alter_friday_day_alter_monday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='monday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='wednessday',
            name='Time',
            field=models.CharField(max_length=8),
        ),
    ]
