# Generated by Django 4.2.1 on 2023-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatAllocation', '0003_alter_friday_time_alter_monday_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wednessday',
            name='NumberOfSeats',
            field=models.IntegerField(),
        ),
    ]
