# Generated by Django 4.2.1 on 2023-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=20)),
                ('EmployeeEmail', models.EmailField(max_length=50)),
                ('EmployeeMobile', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
